server {
    listen 80;
    server_name localhost;
    root /var/www/html;

    location / {
        root /var/www/html/frontend;
        try_files $uri $uri/ /index.html;
    }

    location /backend/ {
        alias /var/www/html/backend/;
        location ~ \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }
}